CREATE TYPE operation_status AS ENUM
(
    'SUCCESS',
    'ALERT_DEFINITION_NOT_FOUND',
    'CHECK_DEFINITION_NOT_ACTIVE',
    'DELETE_NON_LEAF_ALERT_DEFINITION',
    'ALERT_DEFINITION_FIELD_MISSING'
);
